<?php
// Initialize output buffering
ob_start();

function log_msg($msg, $type='info') {
    $icon = "fa-circle-info";
    if ($type == 'success') $icon = "fa-check-circle";
    if ($type == 'error') $icon = "fa-triangle-exclamation";
    
    // Check if we are in CLI mode or simple return
    echo "<div class='log-item $type'><i class='fa-solid $icon'></i> <span>$msg</span></div>";
    ob_flush();
    flush(); 
}

// ---------------------------------------------------------
// PHASE 0: CONFIG WIZARD (If database.php is missing OR broken)
// ---------------------------------------------------------
define('INSTALLER_MODE', true);
$db_connected = false;

if(file_exists("database.php")) {
    require_once("database.php");
    if(isset($db) && $db) {
        $db_connected = true;
    }
}

if(!$db_connected) {
    // ---------------------------------------------------------
    // RENDER: CONFIG WIZARD VIEW
    // ---------------------------------------------------------
    
    // Handle Config Form Submission
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'create_config') {
        $host = $_POST['db_host'];
        $name = $_POST['db_name'];
        $user = $_POST['db_user'];
        $pass = $_POST['db_pass'];
        $url  = $_POST['site_url'];

        // SECURITY FIX: Use var_export() to safely embed values in PHP code.
        // var_export() produces a valid PHP literal with proper escaping,
        // preventing code injection through crafted database credentials.
        $config = "<?php\n\n"
            . "/*\n * Database configuration (auto-generated by installer)\n */\n"
            . '$database = ' . var_export($name, true) . ";\n"
            . '$user = ' . var_export($user, true) . ";\n"
            . '$pass = ' . var_export($pass, true) . ";\n"
            . '$host = ' . var_export($host, true) . ";\n"
            . '$tourneyURL = ' . var_export($url, true) . ";\n\n"
            . '$maxScoreRanks = 3;' . "\n\n"
            . "/* **************** DO NOT EDIT BELOW THIS POINT **************** */\n\n"
            . '$mmm_vers = "ver 1.5.3.7";' . "\n"
            . '$mmm_info = "&copy;" . date(\'Y\') . " OpenBracketChallenge | Orig: &copy;2007-2011 tourney project";' . "\n"
            . '$mmm_authors = "Current: OpenBracketChallenge | Originally based on work by Matt Felser, Brian Battaglia, John Holder, Robert Jailall";' . "\n"
            . '$dbschema_vers = "ver 1.5.2";' . "\n\n"
            . "error_reporting(E_ALL);\n\n"
            . "// Database Connection Safety Logic\n"
            . '$is_placeholder = (' . "\n"
            . '    (isset($database) && $database === \'ncaa\') &&' . "\n"
            . '    (isset($user) && $user === \'username\') &&' . "\n"
            . '    (isset($pass) && $pass === \'pw\')' . "\n"
            . ");\n"
            . '$is_empty = (empty($database) || empty($user) || empty($host));' . "\n\n"
            . 'if ($is_placeholder || $is_empty) {' . "\n"
            . '    if (!defined(\'INSTALLER_MODE\')) {' . "\n"
            . '        require_once __DIR__ . \'/../includes/setup_required.php\';' . "\n"
            . "        exit();\n"
            . "    }\n"
            . "    return;\n"
            . "}\n\n"
            . "try {\n"
            . '    $dsn = "mysql:host=$host;dbname=$database;charset=utf8mb4";' . "\n"
            . '    $options = [' . "\n"
            . "        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n"
            . "        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n"
            . "        PDO::ATTR_EMULATE_PREPARES => false,\n"
            . "    ];\n"
            . '    $db = new PDO($dsn, $user, $pass, $options);' . "\n"
            . '} catch (\PDOException $e) {' . "\n"
            . "    if(defined('INSTALLER_MODE')) return;\n"
            . '    require_once __DIR__ . \'/../includes/service_unavailable.php\';' . "\n"
            . "    exit();\n"
            . "}\n";

        if(file_put_contents("database.php", $config)) {
             header("Location: install.php");
             exit();
        } else {
             $config_error = "Error writing database.php. Check permissions.";
        }
    }
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Setup Database | Bracket Manager</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../css/style.css">
        <link rel="stylesheet" href="../css/all.min.css">
        <style>
            body { background-color: #0f172a; color: #fff; font-family: 'Segoe UI', sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
            .install-container { width: 100%; max-width: 500px; background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 16px; padding: 40px; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5); }
            .form-group { margin-bottom: 20px; }
            .form-group label { display: block; margin-bottom: 8px; color: var(--text-muted); font-weight: 600; }
            .form-group input { width: 100%; padding: 12px; background: #0f172a; border: 1px solid #334155; border-radius: 8px; color: white; box-sizing: border-box; }
            .h-btn { width: 100%; padding: 15px; background: #f97316; color: white; border: none; border-radius: 8px; font-weight: bold; cursor: pointer; font-size: 1.1rem; transition: background 0.2s; }
            .h-btn:hover { background: #ea580c; }
            h1 { text-align: center; margin-bottom: 10px; font-size: 2rem; }
            h1 i { color: #f97316; margin-right: 10px; }
        </style>
    </head>
    <body>
        <div class="install-container">
            <h1><i class="fa-solid fa-server"></i> Database Setup</h1>
            <?php if(isset($config_error)) echo "<div style='background:rgba(239,68,68,0.2); border:1px solid #ef4444; color:#ef4444; padding:10px; border-radius:8px; margin-bottom:20px; text-align:center;'>$config_error</div>"; ?>
            <p style="text-align:center; color:var(--text-muted); margin-bottom:30px;">First, let's connect to your MySQL database.</p>
            
            <form method="post">
                <input type="hidden" name="action" value="create_config">
                <div class="form-group">
                    <label>Database Host</label>
                    <input type="text" name="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label>Database Name</label>
                    <input type="text" name="db_name" value="bracket_db" required>
                </div>
                <div class="form-group">
                    <label>Database User</label>
                    <input type="text" name="db_user" value="root" required>
                </div>
                <div class="form-group">
                    <label>Database Password</label>
                    <input type="password" name="db_pass" placeholder="(Leave empty for none)">
                </div>
                 <div class="form-group">
                    <label>Full Site URL</label>
                    <?php
                        // Dynamically detect path
                        $protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') ? "https" : "http";
                        $host = $_SERVER['HTTP_HOST'];
                        $path = dirname(dirname($_SERVER['SCRIPT_NAME'])); 
                        // SCRIPT_NAME = /tourney/admin/install.php -> dirname = /tourney/admin -> dirname = /tourney
                        $path = rtrim($path, '/\\') . '/'; // Ensure trailing slash
                    ?>
                    <input type="text" name="site_url" value="<?php echo $protocol . "://" . $host . $path; ?>" required>
                </div>
                <button type="submit" class="h-btn">Save Configuration</button>
            </form>
        </div>
    </body>
    </html>
    <?php
    exit(); // Stop here
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Installation Progress | Bracket Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/all.min.css"> 
    <style>
        body {
            background-color: #0f172a; /* Exact match to login/dashboard bg */
            color: #fff;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .install-container {
            width: 100%;
            max-width: 600px;
            background: rgba(30, 41, 59, 0.7); /* Glass dark */
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 40px;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
        }
        .install-header {
            text-align: center;
            margin-bottom: 30px;
        }
        .install-header i {
            font-size: 3rem;
            color: #f97316; /* Orange brand color */
            margin-bottom: 15px;
        }
        .install-header h1 {
            font-size: 2rem;
            margin: 0;
            font-weight: 700;
        }
        .log-box {
            background: rgba(15, 23, 42, 0.6);
            border: 1px solid rgba(255, 255, 255, 0.05);
            border-radius: 8px;
            padding: 20px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 0.95rem;
            color: #cbd5e1;
            margin-bottom: 30px;
            height: 250px;
            overflow-y: auto;
        }
        .log-item {
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .log-item.success i { color: #10b981; }
        .log-item.error i { color: #ef4444; }
        .log-item.info i { color: #3b82f6; }
        
        .action-btn {
            display: block;
            width: 100%;
            padding: 15px;
            background: #f97316;
            color: white;
            text-align: center;
            text-decoration: none;
            font-weight: bold;
            border-radius: 8px;
            transition: all 0.2s;
            font-size: 1.1rem;
        }
        .action-btn:hover {
            background: #ea580c;
            transform: translateY(-2px);
        }
    </style>
</head>
<body>

<div class="install-container">
    <div class="install-header">
        <i class="fa-solid fa-basketball"></i>
        <h1>Installation Manager</h1>
    </div>

    <div class="log-box">
<?php
// ---------------------------------------------------------
// PHASE 1: MAIN INSTALLER (Config exists)
// ---------------------------------------------------------
require_once("database.php"); // Creates $db object

// SECURITY LOCK: Triple-gate — install.lock file + DB meta flag + admin auth
$install_blocked = false;

// Gate 1: install.lock file
if (file_exists("install.lock")) {
    $install_blocked = true;
}

// Gate 2: DB meta flag (installed=1) — catches cases where lock file was deleted but DB is configured
if (!$install_blocked && isset($db) && $db) {
    try {
        $meta_check = $db->query("SELECT COUNT(*) FROM `meta` WHERE `id`=1")->fetchColumn();
        if ($meta_check > 0) {
            $install_blocked = true;
        }
    } catch (PDOException $e) {
        // Table doesn't exist yet — installer should proceed
    }
}

if ($install_blocked) {
    if (file_exists("database.php") && isset($db) && $db) {
        // Fully installed and locked — require admin auth to re-install
        header("Location: ../admin/login.php");
        exit("<h1>Installation Locked</h1><p>The system is already installed. <a href='../admin/login.php'>Go to Admin Login</a>.</p>");
    } else {
        // Lock exists but config missing (Broken state or Intentional Reset)
        echo "<div style='background:#fefce8; color:#a16207; padding:20px; border:1px solid #fde047; margin:20px; border-radius:8px;'>
                <strong>Warning:</strong> An <code>install.lock</code> file was found, but <code>database.php</code> is missing.<br>
                To re-install, please manually delete <code>admin/install.lock</code> via FTP/SSH.
              </div>";
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // ---------------------------------------------------------
    // 1. Run Schema.sql
    // ---------------------------------------------------------
    log_msg("Starting Schema Import...", "info");
    $schema_file = "schema.sql";
    if (file_exists($schema_file)) {
        $sql_content = file_get_contents($schema_file);
        
        // Strip UTF-8 BOM if present
        if (substr($sql_content, 0, 3) === "\xEF\xBB\xBF") {
            $sql_content = substr($sql_content, 3);
        }
        
        // Normalize line endings to LF before splitting
        $sql_content = str_replace(array("\r\n", "\r"), "\n", $sql_content);
        $queries = explode(";", $sql_content);
        
        $errCount = 0;
        foreach ($queries as $query) {
            $query = trim($query);
            if (!empty($query)) {
                try {
                    $db->exec($query);
                } catch (PDOException $e) {
                    // Silent continue for common harmless warnings
                    if(!strpos($e->getMessage(), "already exists")) $errCount++;
                }
            }
        }
        if($errCount === 0) log_msg("Schema Imported Successfully.", "success");
        else log_msg("Schema Imported with minor warnings.", "info");
        
    } else {
        log_msg("Error: schema.sql not found!", "error");
    }

    // ---------------------------------------------------------
    // 2. Insert Meta Configuration
    // ---------------------------------------------------------
    log_msg("Configuring Site Settings...", "info");
    
    $mail = isset($_POST['mail']) ? 1 : 0;
    $sweet16Competition = isset($_POST['sweet16Competition']) ? 1 : 0;

    $deadline = !empty($_POST['deadline']) ? $_POST['deadline'] : null;

    // Sanitize numeric inputs
    $cost = is_numeric($_POST['cost']) ? (float)$_POST['cost'] : 0;
    $cut = is_numeric($_POST['cut']) ? (float)$_POST['cut'] : 0;
    $cutType = is_numeric($_POST['cutType'] ?? '') ? (int)$_POST['cutType'] : 0;

    $metric_ver = defined('APP_VERSION') ? APP_VERSION : '1.0.0';

 
    $meta_sql = "INSERT INTO `meta` (`title`,`subtitle`,`name`,`cost`,`cut`,`cutType`,`email`,`sweet16`,`closed`,`rules`,`mail`,`sweet16Competition`,`region1`,`region2`,`region3`,`region4`,`deadline`,`db_version`,`reg_mode`,`reg_password`,`reg_token`) VALUES (?,?,?,?,?,?,?,0,0,'<p>No additional rules have been set.</p>',?,?,?,?,?,?,?,?,0,'','')";

    try {
        $stmt = $db->prepare($meta_sql);
        $stmt->execute([
            $_POST['title'],
            $_POST['subtitle'],
            $_POST['adminname'],
            $cost,
            $cut,
            $cutType,
            $_POST['email'],
            $mail,
            $sweet16Competition,
            $_POST['region1name'],
            $_POST['region2name'],
            $_POST['region3name'],
            $_POST['region4name'],
            $deadline,
            $metric_ver
        ]);
        log_msg("Meta Configuration Saved.", "success");
    } catch (PDOException $e) {
        log_msg("Meta Insert Failed: " . $e->getMessage(), "error");
    }

    // ---------------------------------------------------------
    // 3. Create Admin User
    // ---------------------------------------------------------
    log_msg("Creating Admin User...", "info");
    $adminName = $_POST['adminname'];
    $hash = password_hash($_POST['password'], PASSWORD_DEFAULT);
    
    try {
        $stmt = $db->prepare("INSERT INTO `admin_users` (`username`, `password_hash`, `role`) VALUES (?, ?, 'super') ON DUPLICATE KEY UPDATE password_hash = ?");
        $stmt->execute([$adminName, $hash, $hash]);
        log_msg("Admin User Created.", "success");
    } catch (PDOException $e) {
        log_msg("Admin User Creation Failed: " . $e->getMessage(), "error");
    }



    // ---------------------------------------------------------
    // 4. Populate Scoring Rules
    // ---------------------------------------------------------
    $db->exec("DELETE FROM `scoring` WHERE type='main'"); 
    
    // SECURITY FIX: Use prepared statements for scoring insert
    $scoring_sql = "INSERT INTO `scoring` (`seed`, `1`, `2`, `3`, `4`, `5`, `6`, `type`) VALUES (?, ?, ?, ?, ?, ?, ?, 'main')";

    try {
        $scoring_stmt = $db->prepare($scoring_sql);
        for( $i=1; $i < 17; $i++ ) {
            $params = [$i];
            for( $j=1; $j < 7; $j++ ) {
                $key = $i."-".$j."_scoring";
                $val = isset($_POST[$key]) && is_numeric($_POST[$key]) ? (int)$_POST[$key] : 1;
                $params[] = $val;
            }
            $scoring_stmt->execute($params);
        }
        log_msg("Scoring Rules Populated.", "success");
    } catch (PDOException $e) {
        log_msg("Scoring Insert Error: " . $e->getMessage(), "error");
    }

    // ---------------------------------------------------------
    // 5. Update Scoring Info
    // ---------------------------------------------------------
    $db->exec("DELETE FROM `scoring_info` WHERE type='main'");
    
    $scoring_res = $db->query("SELECT seed,`1`,`2`,`3`,`4`,`5`,`6` FROM `scoring` WHERE `type` = 'main' ORDER BY `seed`");
    
    $table_text = "<table border='1' align='center'><tr><td colspan='8'>Value of a win by a seed in a particular round</td></tr><tr><td>Seed #</td><td>R1</td><td>R2</td><td>R3</td><td>R4</td><td>R5</td><td>R6</td></tr>";
    
    while ($row = $scoring_res->fetch(PDO::FETCH_ASSOC)) {
        $table_text .=  "<tr><td>".$row['seed']."</td>";
        for( $i=1; $i < 7; $i++ ) {
            $table_text .=  "<td>".$row[$i]."</td>";
        }
        $table_text .=  "</tr>";
    }
    $table_text .= "</table>";
    
    try {
        $stmt = $db->prepare("INSERT INTO `scoring_info` (`type`,`display_name`, `description`) VALUES ('main','Actual', ?)");
        $stmt->execute([$table_text]);
        log_msg("Scoring HTML Generated.", "success");
    } catch(Exception $e) { /* Ignore */ }
    
    // ---------------------------------------------------------
    // 6. Finalize: Create Lock File
    // ---------------------------------------------------------
    $lock_data = "INSTALLED_ON=" . date("Y-m-d H:i:s") . "\nVERSION=" . (defined('APP_VERSION') ? APP_VERSION : 'Unknown');
    file_put_contents("install.lock", $lock_data);

    log_msg("<strong>INSTALLATION COMPLETE!</strong>", "success");

} else {
    // Redirect to the UI to continue installation
    header("Location: install_ui.php");
    exit();
}
?>
    </div> <!-- End Log Box -->

    <?php if ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
        <a href="../admin/login.php" class="action-btn"><i class="fa-solid fa-arrow-right-to-bracket"></i> Continue to Admin Login</a>
    <?php else: ?>
        <p style="text-align:center;">Please use the <a href="install_ui.php" style="color:#f97316;">Configuration Form</a> to start.</p>
    <?php endif; ?>

</div>

</body>
</html>
    

